# Project Information
site_name: 桂圆的笔记
site_url: https://zhuguiyuan.github.io/

# Repository
repo_name: 'zhuguiyuan.github.io'
repo_url: 'https://github.com/zhuguiyuan/zhuguiyuan.github.io'

# Theme
theme:
  name: material
  language: zh
  favicon: assets/favicon.png
  palette:
    primary: white
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes

plugins:
  - search
  - blog:
      blog_dir: .
      blog_toc: true

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Contents
nav:
  - 说说:
    - index.md
  - 关于: about.md
